blank_issues_enabled: false
contact_links:
  - name: Assignment Questions
    url: https://github.com/rhodyprog4ds/BrownFall20/issues
    about: Please ask general questions that might be helpful to your peers here
