name: Prepare for grading
on:
  workflow_dispatch

jobs:
  generatereport:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    # Install dependencies
    - name: Set up Python 3.9
      uses: actions/setup-python@v1
      with:
        python-version: 3.9

    # install dependencies
    - name: dependencies
      run: pip install -r requirements.txt
      #  include quick check

    # generate the report
    - name: Convert notebooks to md for reading
      run: |
        jupytext --to myst *.ipynb
        jupytext --to myst */*.ipynb

    # start a pull request for it
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v4
      with:
        commit-message: 'convert to md'
        draft: false
        branch: published
        base: feedback
        title: Submission
